version: "3.7"
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "8090:9090"
    environment:
      VIRTUAL_HOST: prometheus.finspire.tech
      VIRTUAL_PORT: 8090
      LETSENCRYPT_HOST: prometheus.finspire.tech
      LETSENCRYPT_EMAIL: admin@finspiretech.com
    networks:
      - finspire

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    user: "$UID:$GID"
    environment:
      VIRTUAL_HOST: grafana.finspire.tech
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: grafana.finspire.tech
      LETSENCRYPT_EMAIL: admin@finspiretech.com
      GF_SECURITY_ADMIN_USER: finspire_admin
      GF_SECURITY_ADMIN_PASSWORD: F1nsp1r3@2021
    networks:
      - finspire

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8101:8080
    networks:
      - finspire
    devices:
      - /dev/kmsg

networks:
  finspire:
    name: finspire

volumes:
  prometheus-data:
